# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven and Upload to aws S3

on:
  push:
    branches: [ main ]  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v2
    - name: Step 2 - Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Step 3 - Build with Maven
      run: mvn -B package --file pom.xml
    - name: Step 4 - List the current directory
      run: ls -a
    - name: Step 5 - What is in the target directory?
      run: |
        cd target
        ls -a
    - name: Release to S3
      run: bash scripts/release.sh ${{secrets.AWS_Bucket_Name}} "target/*.jar" ${{secrets.AWS_Access_Key}} ${{secrets.AWS_Access_Secret}}
