###########################################################
# Rename the file extension to ".yaml" (remove "_") to enable
###########################################################

name: Docker Series Builds

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2
      - name: Step 2 - Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Step 3 - Build with Maven
        run: mvn -B clean package --file pom.xml
      - name: Step 4 - List the current directory
        run: ls -a
      - name: Step 5 - What is in the target directory?
        run: |
          ls -a target
      - name: Step 6 - docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Step 7 - docker build java project
        run: |
          docker build . -t ttbackend.jar:1.0.0
      - name: Step 8 - docker tag projects
        run: |
          docker tag ttbackend.jar:1.0.0 parthibandayalan/ttbackend.jar
      - name: Step 9 - docker push
        run: |
          docker push parthibandayalan/ttbackend.jar
